apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: python-based-flask
spec:
  selector:
    app: python-based-flask     # Ensure this label matches your Deployment or Pod label
  type: NodePort
  ports:
    - port: 80                 # Port that the Service will listen on
      targetPort: 5000
      nodePort: 30007         # Port on the Pod to route traffic to (e.g., app’s container port)

